### ISSUE TITLE
Les text_field et les text_area ne fonctionnent  pas...

### ISSUE THREAD

**Issue by DreamLife-ChadY** [AymericBdy/ACsGuis#1]
Un petit problème m'est survenu lorsque j'essayais de créer un "Sqript"  de Register / Login dans un gui.

`on acsguis load:
   register css sheet "sample:css/test.css"

on script load:
	print  "Loaded"

function closeTheGui():
	close current css gui

define gui frame loginGui:
	css_class: "login"
	css_sheets: ["acsgui:css/dnx_debug.css"]
	enable_debug: true
	print "login test gui"
	set {RegTab} to "RegTab"
	set next_tab_pane_name to "Register"
	add css component tabbed_pane with id "tabbed":
		set css "color" to "#FFFFFF"
		set {the_color} to 0xFF00FFFF

		on component render background:
			draw rectangle at  [render_x+0, render_y+0] with size [render_width+10, render_height+10] with color {the_color}
		on component render foreground:
			draw text "Email:" at [render_x+40, render_y+40]
			draw text "Pass:" at [render_x+40, render_y+80]
			add css component text_field
		

on click with minecraft:iron_axe:
	#send "Clicked" to player
	display css gui "loginGui"`
	
	Et  mon  erreur ressemble à ça:
![2022-01-03_04 20 45](https://user-images.githubusercontent.com/49374645/147897691-e8895aab-bffd-4c94-8988-9ba44273301d.png)
 
 
 Merci de m'aider.
 Cordialement Canaane6969

**Comment by AymericBdy** [comment]
Effectivement il y avait un problème dans le code, il est résolu est c'est disponible sur le git. Le fix sera dans la prochaine mise à jour du mod.

**Comment by DreamLife-ChadY** [comment]
> Effectivement il y avait un problème dans le code, il est résolu est c'est disponible sur le git. Le fix sera dans la prochaine mise à jour du mod.

D'acc, merci hum c'est pour quand la prochaine maj?

**Comment by AymericBdy** [comment]
C'est dans la version que j'ai publiée le 7 Janvier du coup.
